### ISSUE TITLE
How to have `laravel` application as a sub-folder?

### ISSUE THREAD

**Issue by ttawan** [ibrunotome/docker-laravel-appengine#1]

**Comment by ibrunotome** [comment]
Hi @ttawan, the gcr.io/google-appengine/php72 will build using files on the root of your project, then will copy all they to the `$APP_DIR`, so your structure will be like:

```
/laravel
├── /app
├── /bootstrap
├── /config
    ├── swoole_http.php
├── /database
├── /public
├── /resources
├── /storage
├── /tests
├── /vendor
├── app.yaml
├── artisan
├── docker-compose.yml
├── Dockerfile
├── fastcgi_params
├── gzip_params
├── nginx.conf
├── nginx-http.conf
├── php.ini
├── php-cli.ini
├── phpunit.xml
├── server.php
├── supervisord.conf
```

If you want to put laravel in a subfolder, with deploy files in the parent folder, you will have to modify the `COPY` line of Dockerfile to copy each app engine file, than copy this subfolder too, something like (just saying, not tested):

```
COPY app.yaml fastcgi_params gzip_params nginx.conf nginx-http.conf php.ini php-cli.ini supervisord.conf laravel_sub_foder/* $APP_DIR
```
