### ISSUE TITLE
Can not build gcr.io/google-appengine/php72:latest

### ISSUE THREAD

**Issue by ttawan** [ibrunotome/docker-laravel-appengine#2]
```
ERROR: Service 'app' failed to build: OCI runtime create failed: container_linux.go:348: starting 
container process caused "exec: \"/bin/sh\": stat /bin/sh: no such file or directory": unknown
```

I've to use 'gcr.io/google-appengine/php72:2018-12-10-13-25' and it building successfully.

**Comment by ibrunotome** [comment]
Hi @ttawan, this is weird, cause the `latest` tag builds successfully on the CI (https://semaphoreci.com/ibrunotome/docker-laravel-appengine) and I also build it with success on my machine. Which version of docker are you using? Try to update your docker to the lasted version:

<img width="582" alt="screenshot 2019-01-17 08 01 28" src="https://user-images.githubusercontent.com/4256471/51310604-29959f00-1a2e-11e9-865a-2e11cd9bca24.png">
