### ISSUE TITLE
Running in production

### ISSUE THREAD

**Issue by williamcastro** [ibrunotome/docker-laravel-appengine#3]
Hello @ibrunotome  congratulations for your work, it's very nice.

I'm using your settings, to run a swoole application (using only the http swoole) in production.
Even if I use docker-compose -d, sometimes the container goes down.

I think it could be because inactivity of container? 
I enabled now, the laravel schedule in supervisor, to try to keep the container up, do you have some tips to do this using your settings for docker?

Thank you.

**Comment by ibrunotome** [comment]
Hello, there is a couple of ways to keep the container alive, you can use the schedule as you did, or in GCP you can create a scheduler to hit a /health endpoint of your application every x minutes.

Also, maybe you can check:

- Update the php container to a most recent version, I stopped to use the provided by google and [start to maintenain my own images](https://github.com/ibrunotome/php/blob/master/7.4/Dockerfile)
- Update swoole version to the latest version (4.4.17) and swooletw/laravel-swoole to the latest version (v2.6.67)
- Check the logs of the container to see if somehting is killing it.

Also, I learned Kubernetes and after that I don't think that there is a motivation to run something on App Engine ever again, maybe you can check https://ibrunotome.github.io/multiplas-aplicacoes-em-um-cluster-kubernetes/

It gives me more flexibility and it's at least 40% less expensive.

**Comment by williamcastro** [comment]
@ibrunotome Hello bruno, thank you for your tips.

To tell the truth i'm not running using Gooel App Engine, I built your image, and did a Deploy to amazon AWS.

In my docker-compose I included "restart: always", and with schedule activated I did not had problem with container going down.
I'll check your new images, to use in new projects.

Thank you for your help!
